config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'friends#index'
  get 'home', to: 'home#index'
  get 'about', to: 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends
  # GET /friends.json
  def index
    @friends = current_user.friends.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
    #@friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = current_user.friends.build(friend_params)
    
    ##@friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice:"Not Authorized" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :insta, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.haml
= form_with(model: friend) do |form|
  - if friend.errors.any?
    #error_explanation
      %h2
        = pluralize(friend.errors.count, "error")
        prohibited this friend from being saved:
      %ul
        - friend.errors.each do |error|
          %li= error.full_message
  .field.form-group.pb-2
    = form.text_field :first_name, class:"form-control", placeholder:"First name"
  .field.form-group.pb-2
    = form.text_field :last_name, class:"form-control", placeholder:"Last name"
  .field.form-group.pb-2
    = form.text_field :email, class:"form-control", placeholder:"Email"
  .field.form-group.pb-2
    = form.text_field :phone, class:"form-control", placeholder:"Phone number"
  .field.form-group.pb-2
    = form.text_field :insta, class:"form-control", placeholder:"Intagram"
  .field.form-group.pb-2
    = form.number_field :user_id, class:"form-control", id: :friend_user_id, placeholder:"User Id", value: current_user.id, type: :hidden
  %br/
  .actions
    = form.submit class:"btn btn-secondary mb-1"

app/views/friends/edit.html.haml
%h1 Editing Friend
%br/
= render 'form', friend: @friend
= link_to 'Show', @friend,class:"btn btn-secondary"
= link_to 'Back', friends_path, class:"btn btn-dark"

app/views/friends/index.html.haml
%h1 Friends
%table.table.table-bordered.table-hover.table-striped
  %thead.table-dark
    %tr
      %th Name
      %th Email
      %th Phone
      %th Insta
      %th{:colspan => "2"}
  %tbody
    - @friends.each do |friend|
      %tr
        %td= link_to friend.first_name + ' ' + friend.last_name, friend
        %td= friend.email
        %td= friend.phone
        %td= friend.insta
        %td= link_to 'Edit', edit_friend_path(friend), class:"btn btn-success btn-sm"
        %td= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm"
%br/
= link_to 'New Friend', new_friend_path, class:"btn btn-secondary"

app/views/friends/new.html.haml
%h1 Add New Friend
%br/
= render 'form', friend: @friend
= link_to 'Back', friends_path, class:"btn btn-dark"

app/views/friends/show.html.haml
.p-5{:style => "background-color:#c6c6c6"}
  %h1.p-4
    = @friend.first_name
    = @friend.last_name
  %p.p-4
    = @friend.email
    | #{@friend.phone} | #{@friend.insta}
  = link_to 'Edit', edit_friend_path(@friend), class:"ms-4 btn btn-secondary"
  = link_to 'Back', friends_path, class:" btn btn-dark"

app/views/home/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container-fluid
    = link_to 'Friends App', root_path, class:"navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          = link_to "About Us", about_path, class:"nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to "Add Friend", new_friend_path, class:"nav-link"
          %li.nav-item
            = link_to "Sign Out", destroy_user_session_path,method: :delete, class:"nav-link"
          %li.nav-item
            = link_to "Edit Profil", edit_user_registration_path, class:"nav-link"
        - else
          %li.nav-item
            = link_to "Sign Up", new_user_registration_path, class:"nav-link"
          %li.nav-item
            = link_to "Sign In", new_user_session_path, class:"nav-link"

app/views/home/about.html.haml
%h1 About us

app/views/home/index.html.haml
%h1 home index

app/views/layouts/_alerts.html.haml
.alert.alert-warning.alert-dismissible.fade.show{:role => "alert"}
  = notice
  %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Bootstrap CSS
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css", :integrity => "sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1", :rel => "stylesheet"}/
    %title Friends
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'home/header'
    .container
      %br/
      - if notice
        = render 'layouts/alerts'
      = yield
    / Optional JavaScript; choose one of the two!
    / Option 1: Bootstrap Bundle with Popper
    %script{:crossorigin => "anonymous", :integrity => "sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"}
    / Option 2: Separate Popper and Bootstrap JS
    /
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>